import { Cross, Crosshair, CrossIcon, Icon, LucideMoreVertical, Plus, Search, Send, Smile } from 'lucide-react'
import React, { useState,useEffect,useMemo } from 'react'
import io from 'socket.io-client'
import Navbar from './Navbar'

let socket = io('http://localhost:8000',{
     reconnection:true,
     reconnectionAttempts:5,
     reconnectionDelay:1000,
})

const MessageContainer = () => {

const [message,updatemessage] = useState('');
const [data,updatedata] = useState(['hi','I am second sms auto generated by dheeraj ','i am third message']);

  useEffect(()=>{
    socket.on('receive_message',(data)=>{
     console.log(data)
     updatedata((prev)=>[...prev,data])
  });

    return ()=>{
      socket.off('receive_message')
    }
  },[])


  return (
     <>

    <div className='hidden md:flex flex-1 min-h-0 relative flex-col'>
     <Navbar/>
     <div className='flex justify-between bg-black opacity-90 px-6 py-4'>
          <div className='flex flex-row w-full  gap-4 '>
               <img  className='h-12 w-12 rounded-full bg-blue-400'></img>
               <p className='text-xl text-white my-auto'>Name </p>
          </div>
          <div className='flex flex-row my-auto gap-4'>
               <Search color='white' className='cursor-pointer'/>
               <LucideMoreVertical color='white' className='cursor-pointer'/>
               
          </div>
     </div>


     <div className='flex flex-col gap-2  bg-[#212121] flex-1'>
      {
      data.map((msg,idx)=>{
          return( <Message data={msg}/> )
      })
     }
      </div>
      <TypeMessage message={message} updatemessage={updatemessage}/>

    </div>

    </>
  )

}

export default MessageContainer


const Message = ({data})=>{
     return(
          <div className='bg-white rounded-xl  py-2 px-4 inline-block relative min-w-32 max-w-60 wrap-break-word mx-8 my-4'>
               <p className='mb-2 '>{data}</p>
               <div className='flex flex-row absolute bottom-0 right-1 text-xs'>
                    <p>message time</p>
                    <p>status</p>
               </div>
          </div>
     )
}

const TypeMessage = ({message,updatemessage})=>{
     
     const sendmessage = (e)=>{
     e.preventDefault()
     if(message!==''){
          socket.emit('send_message',message)
          updatemessage('')
     }
     
}
     const updatemsg = (e)=>{
          e.preventDefault()
          updatemessage(e.target.value)
     }

     return(
          <div className='absolute bottom-4 w-full'>
          <div className='gap-2 bg-white m-auto w-[95%]  flex flex-row px-4 py-4 rounded-2xl'>
               <Plus/>
               <Smile/>
               <input
                    value={message}
                    onChange={updatemsg}
               type='text' placeholder='type...' className='flex-1  active:outline-none hover:outline-none focus:outline-none'></input>
               <Send 
                onClick={sendmessage}/>
          </div>
          </div>   
     )
}